// Email Service - Send AI-generated call reports via email
// Uses mailto: protocol to open user's email client with pre-filled content

import { generateIssueSummary } from './analyticsService';

/**
 * Generate HTML email content for call report
 */
export const generateCallReportEmail = (call) => {
  const issueSummary = generateIssueSummary(call.callType, call.riskLevel);
  
  // SOP Checklist
  const sopChecklist = [
    { step: 'Greeting & Introduction', done: true },
    { step: 'ID Verification', done: (call.sopAdherence || 75) > 70 },
    { step: 'Problem Understanding', done: true },
    { step: 'Solution Provided', done: true },
    { step: 'Upsell Attempt', done: (call.sopAdherence || 75) > 80 },
    { step: 'Closing Script', done: (call.sopAdherence || 75) > 60 },
  ];

  const sopChecklistText = sopChecklist
    .map(item => `${item.done ? '✅' : '❌'} ${item.step}`)
    .join('\n');

  const issuesText = call.issues && call.issues.length > 0 
    ? call.issues.map(issue => `• ${issue}`).join('\n')
    : 'No critical issues detected';

  const suggestedAction = call.sopAdherence < 70 
    ? 'Schedule immediate 1-on-1 coaching session with supervisor'
    : call.sopAdherence < 80 
      ? 'Review SOP guidelines with agent during next team meeting'
      : 'Positive feedback - continue current practices';

  return {
    subject: `🚨 Smart-Audit AI Alert: ${call.riskLevel?.toUpperCase()} Risk Call - ${call.agent} (${call.id})`,
    body: `
═══════════════════════════════════════════════════
🔋 SMART-AUDIT AI - CALL ANALYSIS REPORT
═══════════════════════════════════════════════════

📋 CALL DETAILS
───────────────────────────────────────
• Call ID: ${call.id || 'N/A'}
• Agent Name: ${call.agent || 'Unknown'}
• Customer Phone: ${call.callingNo || 'N/A'}
• City: ${call.city || 'Unknown'}
• Call Date: ${call.callDate || new Date().toLocaleDateString()}
• Duration: ${call.duration || '5:30'}
• Risk Level: ${(call.riskLevel || 'medium').toUpperCase()}

═══════════════════════════════════════════════════
🎯 ISSUE SUMMARY (Why Customer Called)
═══════════════════════════════════════════════════
${issueSummary}
Call Type: ${call.callType || 'General Inquiry'}

═══════════════════════════════════════════════════
📊 QUALITY METRICS
═══════════════════════════════════════════════════
• QA Score: ${call.qaScore || call.sopAdherence || 75}%
• SOP Adherence: ${call.sopAdherence || 75}%
• Customer Sentiment: ${(call.sentiment || 'neutral').toUpperCase()}

═══════════════════════════════════════════════════
🤖 AI-GENERATED ANALYSIS
═══════════════════════════════════════════════════
${call.summary || 'Call analyzed successfully. Agent followed most SOP steps. Customer issue was addressed during the call.'}

═══════════════════════════════════════════════════
⚠️ DETECTED ISSUES
═══════════════════════════════════════════════════
${issuesText}

═══════════════════════════════════════════════════
💡 SUGGESTED ACTION
═══════════════════════════════════════════════════
${suggestedAction}

═══════════════════════════════════════════════════
✅ SOP CHECKLIST
═══════════════════════════════════════════════════
${sopChecklistText}

═══════════════════════════════════════════════════
🔊 AUDIO RECORDING
═══════════════════════════════════════════════════
${call.audioUrl || 'Audio not available'}

═══════════════════════════════════════════════════

Generated by Smart-Audit AI
Battery Smart Intelligence Platform
Date: ${new Date().toLocaleString()}

---
This is an automated report from the Smart-Audit AI system.
For questions, contact your supervisor or the QA team.
`.trim()
  };
};

/**
 * Generate supervisor alert email
 */
export const generateSupervisorAlertEmail = (alert, call) => {
  const report = generateCallReportEmail(call || alert);
  
  return {
    subject: `🚨 CRITICAL ALERT: ${alert.priority?.toUpperCase()} Priority - Agent ${alert.agent} requires immediate attention`,
    body: `
═══════════════════════════════════════════════════
⚠️ SUPERVISOR ALERT - IMMEDIATE ACTION REQUIRED
═══════════════════════════════════════════════════

Priority: ${(alert.priority || 'high').toUpperCase()}
Agent: ${alert.agent}
Call ID: ${alert.callId || alert.id}
Time: ${alert.timestamp || new Date().toLocaleTimeString()}

REASON FOR ALERT:
${alert.reason || 'Low SOP adherence detected'}

AI SUMMARY:
${alert.summary || 'This call requires supervisor review due to compliance issues.'}

───────────────────────────────────────

${report.body}
`.trim()
  };
};

/**
 * Open email client with pre-filled report
 */
export const sendCallReportEmail = (call, recipientEmail = '') => {
  const report = generateCallReportEmail(call);
  
  // Encode for mailto URL
  const encodedSubject = encodeURIComponent(report.subject);
  const encodedBody = encodeURIComponent(report.body);
  
  // Create mailto link
  const mailtoUrl = `mailto:${recipientEmail}?subject=${encodedSubject}&body=${encodedBody}`;
  
  // Open email client
  window.open(mailtoUrl, '_blank');
  
  return { success: true, message: 'Email client opened with report' };
};

/**
 * Open email client with supervisor alert
 */
export const sendSupervisorAlertEmail = (alert, call, recipientEmail = '') => {
  const report = generateSupervisorAlertEmail(alert, call);
  
  // Encode for mailto URL
  const encodedSubject = encodeURIComponent(report.subject);
  const encodedBody = encodeURIComponent(report.body);
  
  // Create mailto link
  const mailtoUrl = `mailto:${recipientEmail}?subject=${encodedSubject}&body=${encodedBody}`;
  
  // Open email client
  window.open(mailtoUrl, '_blank');
  
  return { success: true, message: 'Email client opened with alert report' };
};

/**
 * Copy report to clipboard (alternative to email)
 */
export const copyReportToClipboard = async (call) => {
  const report = generateCallReportEmail(call);
  const fullText = `${report.subject}\n\n${report.body}`;
  
  try {
    await navigator.clipboard.writeText(fullText);
    return { success: true, message: 'Report copied to clipboard!' };
  } catch (error) {
    console.error('Failed to copy:', error);
    return { success: false, message: 'Failed to copy report' };
  }
};

export default {
  generateCallReportEmail,
  generateSupervisorAlertEmail,
  sendCallReportEmail,
  sendSupervisorAlertEmail,
  copyReportToClipboard,
};
